### ISSUE TITLE
Grid issues after location switch (0.11.5)

### ISSUE THREAD

**Issue by Purzelkater** [Kruptein/PlanarAlly#105] opened 2018-11-10 12:39 UTC
1) The grid is shown after every location switch even if grid is deactivated for the location on DM options.
2) If I set Grid Unit size to 0.5 it will be changed to 0 after location switch (this was working on older versions I think).

**Comment by Kruptein** [comment] 2018-11-10 13:14
1. Is something I cannot seem to reproduce
2. This is due to the server storing the size as an integer instead of a floating point number, which makes it 0 which in turn gets reverted to the default value as 0 is not allowed

Is there a reason why you're using such a small grid size?

**Comment by Purzelkater** [comment] 2018-11-10 14:07
1) I have added a picture with 3 screenshots. On the first you can see the Nerissa location, grid is off. Then I have switched to start location, where grid is off too, but shown. Then I habe switched back to Nerissa location and grid is shown but setting has not changed.
I have tried logout/login without success.
2) Well, this is because I use the grid as metric style (I edit the js file in static folder to show 1 decimal digit with a "m" instead of "ft"). So the grid size of 0,5 x 0,5 meters is very nice for the token size on the maps and they fits great with this too.

![pa_grid](https://user-images.githubusercontent.com/44810275/48302167-23001e00-e4f9-11e8-90a7-a1c638d1c562.jpg)

**Comment by Purzelkater** [comment] 2018-11-10 14:54
Sadly there is no message on python console and no error on chrome console too. I have tried again with a new "installation" and without old saves, but the same effect.
btw: If I reload the the page with F5, the grid is not shown at first, but is shown after the first location switch.
btw2: Have the same gird problem with firefox and Microsoft edge too. :(

Thank you for changing the grid size setting. :)

**Comment by Kruptein** [comment] 2018-11-10 15:38
It's good that you have a temp fix, but those should not be equal if the old location had a grid and the new doesn't (or vice versa)

**Comment by Purzelkater** [comment] 2018-11-10 15:49
You are right, if last und actual location has the same grid setting, it works out of the box. If last and actual location has grid on, it works out of the box too. But if last and actual location has set grid off it fails. Could it be the default setting is grid on and display none is not fired on location switch again because the saved setting is the same (grid oft) but not synced to the canvas or like that?

**Comment by Kruptein** [comment] 2018-11-10 18:02
I've added the change of the grid size to decimals in the dev branch.

On startup the program should attempt to upgrade your database to apply the change.
, so you should not have to do anything.

**Comment by Purzelkater** [comment] 2018-11-10 19:47
Thank you! :)

I had to change `unit_size = IntegerField(default=5)` to `unit_size = FloatField(default=5)` on `campaign.py` too but now it works fine.

**Comment by Kruptein** [comment] 2018-11-10 19:54
it's grid_size though, not unit_size

**Comment by Kruptein** [comment] 2018-11-10 19:55
https://github.com/Kruptein/PlanarAlly/blob/dev/PlanarAlly/models/campaign.py#L208

**Comment by Kruptein** [comment] 2018-11-10 19:59
haha my bad, I thought you were talking about the grid size all this time, not the unit size

**Comment by Kruptein** [comment] 2018-11-10 20:44
Well that's been changed on dev as well.

Regarding the other problem you have, I'm not gonna include your temp fix in that regard in the main codebase as ideally it should just work as is, so I rather find the actual bug before having to resort to the bandaid fix, but it's good you have something in the meanwhile :)

**Comment by Kruptein** [comment] 2019-02-14 20:17
I've not been able to reproduce it so far, I'm gonna close it for now, if you still have the problem on the newest version, feel free to reopen it.

**Closed by Kruptein** 2019-02-14 20:17 UTC
Labels: bug
