### ISSUE TITLE
[FEAT] A vision-blocking object should only block the area behind it, not itself

### ISSUE THREAD

**Issue by refparo** [Kruptein/PlanarAlly#1324] opened 2023-11-25 13:10 UTC
**Is your feature request related to a problem? Please describe.**
When I set a shape to "block vision", it blocks not only the area away from the player character's line of sight, but also itself, making itself a black shape. For example, when a tree trunk is set to "block vision", I want to prevent my players seeing things after the trunk, but I also want to allow them to see the trunk itself, while PlanarAlly currently shows the trunk as a black circle.

**Describe the solution you'd like**
Players should be able to see the vision-blocking shapes.

**Describe alternatives you've considered**
I have tried to emulate this kind of effect by making the shape emit a light that covers only itself. However, this doesn't work when the shape is in the dimming area of a player's area of sight. (It doesn't dim along with the area)

**Additional context**
None.

**Comment by Kruptein** [comment] 2023-11-27 19:08
Hey, this is also something that has irked me in the past.

A naïve solution would be to just exclude themselves, however in the current way lighting is done, this means that the entirety of that object is ignored for vision. When reading this you might be confused as that probably sounds right. And this is fine for small objects, a rock or a tree trunk is indeed something you'll probably see in its entirety most of the time.

There are however 2 issues (that I experienced):
- Suppose you have some dungeon and you have decided to use thick rectangles to block out the walls. If a player walks past the wall they'll see these 30ft thick walls and then suddenly there is a thin wall, without doors. Our secret hidden room has been spoiled! (note: In practice I personally use the polygon tool for walls so it wouldn't really apply to me)
- A side-effect of the current lighting/vision implementation I wasn't able to resolve when I did a stab at this a couple of months ago, was that it wasn't possible to limit what you saw of vision-blocking items to just that which fell within a light aura. Instead if your vision covered part of the object, you saw the entire object.

Now with this monologue out of the way, there is a cheap solution to offer what you're looking for: Make it a new optional toggle per shape. In that case you could mark your tree trunk or a door as some new property which would exclude itself and reveal its entirety, which for small shapes should be fine.

It's just a bit more work on the DM's end to toggle this.

I would like to tackle this more properly at one point, especially (2) as for (1) I actually don't know if there is a proper solution.

Would this toggle be an acceptable solution for you ?

**Comment by develroo** [comment] 2023-11-28 09:53
> Now with this monologue out of the way, there is a cheap solution to offer what you're looking for: Make it a new optional toggle per shape. In that case you could mark your tree trunk or a door as some new property which would exclude itself and reveal its entirety, which for small shapes should be fine.


The simplest option would be instead of just an `invisible` tick box you have a `Always visable` tick box, which will still follow FOW rendering but just mean when a PC sees it, it is visible despite blocking light or movement. That is how I envision it, anyway.

**Comment by develroo** [comment] 2023-11-28 10:01
> * Supposing I have a dungeon with rectangular walls, I would mark them as blocking vision which would operate as it currently does and not allow seeing the shape at all and blocking all vision behind the shape. Then I would draw a 'Reveal When In Vision' rectangle over top of the wall but inset slightly to only allow seeing part of it, allowing the GM to prevent showing spoilers by revealing the entire shape of the wall.

What I do, really depends on the underlying map. For secret doors it has always been a square block that is marked out on the DMs map. That is never a problem, really. (see video)

But for visible doors it is a little trickier as when you make a token block light it is blocking itself at the same time.
[Screencast from 2023-11-28 09-58-38.webm](https://github.com/Kruptein/PlanarAlly/assets/7777993/ea0d69ce-84aa-4d14-aac9-4b3acc666076)

**Comment by refparo** [comment] 2023-11-29 09:51
I don't know how lighting in PA works, but my intuitive solution is: to cast lights from the character to everything around them, and each ray of light ends when they exit an object (instead of when entering an object). If this can be implemented in code, it should solve the issue (2) you mentioned, but not issue (1).

As for issue (1), I think I would cut the secret room from the map to make it an individual object, and only make it visible when it's discovered...

**Comment by develroo** [comment] 2023-11-29 12:50
> As for issue (1), I think I would cut the secret room from the map to make it a separate object, and only make it visible when it's discovered...

That is essentially what I already do for both doors and secret doors when making a map mask. The issue is not so visible in maps where the door symbols are drawn, and it is easy for the player to see them despite a line representing the actual door. 

The problem come when the map doesn't have doors that stand proud and align with the actual wall. Then, even adding a new object to stick out covers the object behind it. 

The solution I have settled on atm which is a bit of a faff to do for every door, is to lay a door asset in place, and then draw a line as the blocking part. This works, but
![Screenshot from 2023-11-29 12-47-26](https://github.com/Kruptein/PlanarAlly/assets/7777993/2f88488e-1d22-42fe-a1d8-8ccfd5493a9b)
![Screenshot from 2023-11-29 12-47-12](https://github.com/Kruptein/PlanarAlly/assets/7777993/c4be61b2-fb85-4615-87ed-6fbc6bf0803a)
 it is inconvenient if you have hundreds of doors to place.

**Comment by Kruptein** [comment] 2023-12-11 22:09
I actually made an implementation that seems to work. If people running dev want to check it out and provide me with feedback that would always be appreciated.

It does not change the save file format, so you can freely swap between dev and the branch in the linked PR above freely at this point in time. (the notes PR that is in progress _does_ change the save format)

**Comment by develroo** [comment] 2023-12-11 22:30
> I actually made an implementation that seems to work. If people running dev want to check it out and provide me with feedback that would always be appreciated.
> 
> It does not change the save file format, so you can freely swap between dev and the branch in the linked PR above freely at this point in time. (the notes PR that is in progress _does_ change the save format)

Well am running dev is this the right commit? 

```
commit c802dbde8f7666a97cf71c65b7192a83896b906d (HEAD -> dev, origin/dev, origin/HEAD)
Author: Darragh Van Tichelen <info@darragh.dev>
Date:   Wed Dec 6 22:24:37 2023 +0100

    bug(Ruler): Fix server log spam

```

**Comment by Kruptein** [comment] 2023-12-11 22:32
You need to change to the branch in the linked PR

**Comment by develroo** [comment] 2023-12-11 22:43
WOOT! seem to work in my specific example. All I hade to do was move the token from a layer to another for some reason but it works as intended with the metal door token and the door bar on the same layer and the Fake player can see the handles but not what is behing the door. 

Thanks so much for tackling this quickly. It was becoming and issue in places like this. 


https://github.com/Kruptein/PlanarAlly/assets/7777993/48333b22-8394-42d7-a8c8-de8f2a5b0568

**Comment by develroo** [comment] 2023-12-11 22:52
Hehe.. ok .. So not a bug exactly but I am wondering how easy it would be to make shadows fade away like light does to make this sort of scene seem more realstic.

![Screenshot from 2023-12-11 22-51-59](https://github.com/Kruptein/PlanarAlly/assets/7777993/9f2a7785-e0be-4abb-9e4a-1644c4145972)
![Screenshot from 2023-12-11 22-51-49](https://github.com/Kruptein/PlanarAlly/assets/7777993/db6d4977-cd8e-4dd3-88a0-f0f4142c1ceb)

**Comment by Kruptein** [comment] 2023-12-15 18:55
That doesn't sound easy to accomplish, so it's definitely out of scope for now.

**Comment by Kruptein** [comment] 2023-12-15 18:56
This is now supported as a new vision blocking mode!

**Closed by Kruptein** 2023-12-15 18:56 UTC
