### ISSUE TITLE
[BUG] Initiative Windows Issues

### ISSUE THREAD

**Issue by JackRyan88** [Kruptein/PlanarAlly#350] opened 2020-05-17 09:15 UTC
Hey all, 

we did a session yesterday and faced again some problems with the initiative window. 

Three major points:

1) When every player puts the ini in at the same time, at the end some inis are not saved.

2) When players itself want to add effects (e.g. haste or something) in there, it sometimes vanishes after time (we didn't actually tested this in excess, but I got the feeling that it will be deleted after the beginning of next round)

3) The order of the ini is sometimes not correctly displayed, e.g. someone with higher number is below someone with a lower number. This is also not the same on all player displays, so it happened that someone said it looks correct and the dm had a wrong order on his side

We were using yesterday the newest dev branch version (0.20.1-8-gb8320c1), but we also got this issues in the past versions and the newest release version. 

Thank you, especially @Kruptein, for your effort in making and further developing this!

**Comment by dthv** [comment] 2020-05-17 11:46
> When players itself want to add effects (e.g. haste or something) in there, it sometimes vanishes after time (we didn't actually tested this in excess, but I got the feeling that it will be deleted after the beginning of next round)

Did you add a duration? Right of the effect description, there is a field to insert an integer (i.e. a natural number like 1, 5 or 12). This is the duration of the effect in rounds. After one round, i.e. by the start of the next turn of said player, this number decreases by one. Instead of staying with 0 or going negative, by reaching 0, the effect is deleted from the list since it expired.

**Comment by JackRyan88** [comment] 2020-05-18 06:28
Thank you for your reply. Yes, we added always durations as this is what we wanted to track. We believe it has something to do with players adding the initiative and effects as when the DM does it it works better (not all the time but most of the time). So we switched some sessions and version ago to that mode but after the latest dev built we tried again, and same issue.

**Comment by Kruptein** [comment] 2020-05-20 19:25
1 and 2 should be resolved and their changes merged in dev.

Do you have some idea on how to reproduce 3 ?

**Comment by Kruptein** [comment] 2021-05-16 07:10
This should be fully resolved in dev at this point

**Closed by Kruptein** 2021-05-16 07:10 UTC
Labels: Client, bug
