### ISSUE TITLE
Token creation isn't sticking or showing up for players

### ISSUE THREAD

**Issue by poltergeisha** [Kruptein/PlanarAlly#108] opened 2018-11-17 04:28 UTC
We've been using Planar Ally for weeks now and it was working great, and I noticed that the red/black dot bug is gone, but now there seems to be a problem with saving created / dragged out tokens on the page. My players are only seeing like every few tokens I create, and when I refresh or move to a different page, they disappear for me too. After a while a map just quits saving new basic tokens at all.

**Comment by poltergeisha** [comment] 2018-11-17 04:41
If I create a token on the map layer it seems to stick, but if I move it to the token layer and then it stops sticking and reverts to the map layer on refresh.

**Comment by Kruptein** [comment] 2018-11-17 06:11
Seems like you had a frustrating session due to PA, sorry :( I'll try to
fix this asap

**Comment by Kruptein** [comment] 2018-11-17 07:48
Can I ask you which version you were running? (or branch)

You can find the version in the changelog

**Comment by Kruptein** [comment] 2018-11-17 13:43
I've found a bug related to changing a shape's layer, so that would definitely explain certain things always reverting to the map layer on refresh.

I'm not sure yet what could cause shapes to actually get removed/disappear.

I suppose you don't host the server yourself so you don't see the errors.

**Comment by Kruptein** [comment] 2018-11-17 14:11
The shape layer change bug should be fixed on the dev branch now.

**Comment by poltergeisha** [comment] 2018-11-17 17:41
I use the dndbox version. :) Also another somewhat related issue is that it seemed like the view (which map I was on) wasn't always updating for my players either.  If they refreshed, they were shunted back to the first view page, and I had to re-click on my current page to get them back, and then none of my changes were saved either.

I suppose I really should host this myself so I can at least have a backup of the latest stable release, since Planar Ally is so important to my game. I have a basic AWS subscription.....just no idea how to even begin hosting it myself. 😅 I've only ever done basic discord bot hosting.

**Comment by poltergeisha** [comment] 2018-11-28 18:31
Update: 

The other GM in our group decided to take a gamble with PA again last week (using dndbox so we don't have the latest dev version, only whatever release schemen uses) and we we able to get it to limp along. We discovered:

- Tokens created by the GM before any players log on **do** seem to stick between refreshes.
- Tokens created by the GM while players are logged on **don't** always stick between refreshes and disappear.
- Tokens created by players seem to always stick.
- When players refreshed their page they were kicked back to the start page, and the GM had to click on the map in the top bar again to bring them back to it it.

**Comment by Kruptein** [comment] 2018-11-29 08:33
I believe I've fixed this on the dev branch already, i'll try and see if I can reproduce it with the info you've given.

**Comment by poltergeisha** [comment] 2018-11-30 16:05
I may dive into seeing if I can get planar ally hosted somewhere myself soon, because I would then have control over the version we're using.  There is a very good chance this will be really far over my head but I can try 😂

**Comment by Kruptein** [comment] 2019-02-15 21:51
I'm gonna close this for now, if it appears to still be a problem feel free to reopen it

**Closed by Kruptein** 2019-02-15 21:51 UTC
Labels: bug
