### ISSUE TITLE
In-Person use improvements

### ISSUE THREAD

**Issue by schemen** [Kruptein/PlanarAlly#129] opened 2019-02-05 22:23 UTC
Heya!

My main usage for PlanarAlly is for in-person use (A flat screen on the table). Any chance we could add/improve some features?
I had some ideas in my mind of the likes:

* Make it possible to scale the player view from the dm screen (so I can get the correct size for minies)
* Remove all UI elements on the player view
* Simpler "Move Players here" method, currently only possible with the select tool and right click. Maybe have it on right click all the time on all layers

This could extend to a In-Person mode which removes all the dynamic lighting stuff to declutter UI elements.

Cheers!

**Comment by Kruptein** [comment] 2019-02-05 22:34
Hey,

Could you clarify some things?

What exactly do you mean with scale a player view as the dm? Do you mean
controlling the zoom level of that player from the dm side while still
having a separate dm zoom level, or simply mimicking the dm zoom?

Could you elaborate in which way the lighting clutters the ui in your
opinion?

Thanks for using PA and providing feedback, I'll see what I can do :)

**Comment by schemen** [comment] 2019-02-05 22:43
Yeah of course!

> What exactly do you mean with scale a player view as the dm? Do you mean controlling the zoom level of that player from the dm side while still having a separate dm zoom level, or simply mimicking the dm zoom?
Hm, both sound good. First one could be achieved by having two sliders - secondly could be achieved easier I suppose. But yes, I mean the zoom level so the minies fit the screen. The "Bring Players here" is already available and great, now something like that for zoom as well :) or maybe even a static setting per map (like FOW Opacity level - as screen size doesn't really change and thus the zoom doesn't as well - I might even like this option the best, lol)

> Could you elaborate in which way the lighting clutters the ui in your opinion?
I just thought it would make the UI more lightweight, I might be off though!


Btw, planarally on dndbox is running very stable, looking at the logs & resource stats I am very happy with it! There is actually quiet a few people using it fairly regular :D

**Comment by Kruptein** [comment] 2019-02-06 09:32
Hm, I'll have to think about it to make sure I add it in such a way that it does not hamper any other users.

That being said, disabling the UI is definitely easy to add.

Nice to hear that it's running smooth!

**Comment by AJAnderson** [comment] 2019-02-08 20:27
I second being able to disable the UI, particularly on the player screen.

**Comment by Kruptein** [comment] 2019-02-15 22:12
Toggling of UI can now be done on the dev branch with `ctrl+u`

**Comment by dthv** [comment] 2021-02-16 23:36
As far as I see it, there is only one part of this issue that can be considered still open:

>     * Make it possible to scale the player view from the dm screen (so I can get the correct size for minies)

With all the changes to the grid options, I'm not entirely sure that it actually is, though. Also, a possible solution to this issue would possibly be a duplicate of #285 and parts of #197, respectively.

The reason for this issue necromancy is the following: What about a DM-controlled spectator whose viewport is represented as a dragable (resulting in pan) and resizeable (resulting in zoom) rectangle at at the GM's gameboard? Of course, relevant client settings (grid size etc.) should be modifiable by the GM, as well.

@schemen I saw the photo of your table at the Discord. Would that be a solution you could work with?
(and of course: @Kruptein do- and likeable? :slightly_smiling_face: )

**Comment by Kruptein** [comment] 2021-06-20 15:35
With the addition of the DM viewport and mini size grid settings, this can now be closed.

Also @dthv somehow I totally missed your comment here, and someone else happened to suggest the same thing with the rectangle to me, which I ended up implementing ;D

**Closed by Kruptein** 2021-06-20 15:35 UTC
Labels: enhancement
