### ISSUE TITLE
[BUG] Firefox visual problem

### ISSUE THREAD

**Issue by jirsat** [Kruptein/PlanarAlly#364] opened 2020-05-22 12:39 UTC
**Describe the bug**
On Firefox, there is a scrollbar, which can mess up a visual (UI moves to left - out of sight, maps stays but starts to get hidden behind background). Can be also triggered by using middle mouse to pan. 

**To Reproduce**
1. Use middle mouse to pan screen while in game

**Screenshots**
![image](https://user-images.githubusercontent.com/45206873/82668205-91b74f00-9c39-11ea-931d-26c1191cc4c5.png)

**Desktop (please complete the following information):**
 - OS: Linux, Windows
 - Browser: Firefox
 - Version 20.1

**Additional context**
Tested on one and two screen setup. On chrome works as expected (no bug).

**Comment by Kruptein** [comment] 2020-05-22 13:11
I don't have this when the window is maximized, but seem to have it when it is smaller.

**Comment by jirsat** [comment] 2020-05-22 13:47
That's weird, I have it always as DM

**Comment by Kruptein** [comment] 2020-05-22 14:28
Well whether it only happens in smaller windows or not, it should be fixed.  Nice map btw ;)

**Comment by Kruptein** [comment] 2020-05-24 20:44
And now I can't reproduce it anymore at all 🙃

**Comment by Kruptein** [comment] 2020-06-01 15:18
Thanks to @FrederikGoovaerts I now know that this is due to the location scrollbar misbehaving on firefox.  This only occurs if the number of locations cannot fit the location bar.

**Closed** 2020-06-01 16:07 UTC
Labels: UI, bug
