### ISSUE TITLE
[BUG] Character deletion breaks database

### ISSUE THREAD

**Issue by rexy712** [Kruptein/PlanarAlly#1511] opened 2024-11-11 04:28 UTC
**Describe the bug**
I direct messaged you about the database issue involving Characters in some way. I didn't report this on github previously because I hadn't tried to recreate the issue, but I believe now I found the cause. It was the deletion of a Character that caused it. No other steps required. Not deletion of the shape, but of the Character.

**To Reproduce**
1. Create a Character.
2. In the sidebar, hit the 'Remove Character' button
3. Confirm
4. Refresh
5. Infinite loading screen, error in server logs.

**Expected behavior**
Remove the Character and not the shape.

**Screenshots**

https://github.com/user-attachments/assets/85f47ab0-1482-4126-b243-d4b413f14878

**Desktop:**
 - OS: gentoo linux
 - Browser: ungoogled-chromium 130.0.6723.58
 - Version: dev branch commit [5221159](https://github.com/Kruptein/PlanarAlly/commit/5221159296e532c3d4ec21af395149446b3a8d98)

**Additional context**
This is the server log:
```
${TIME_OF_OCCURANCE} - CRITICAL - Uncaught async exception <Model: AssetRect> instance matching query does not exist:
SQL: SELECT "t1"."shape_id", "t1"."width", "t1"."height", "t1"."src" FROM "asset_rect" AS "t1" WHERE ("t1"."shape_id" = ?) LIMIT ? OFFSET ?
Params: ['abeff924-818b-45c9-bd75-a63c286f6c7e', 1, 0] (logs.py:38)
Task exception was never retrieved
future: <Task finished name='Task-15570' coro=<AsyncServer._handle_event_internal() done, defined at ${PLANARALLY_DIR}/server/venv/lib/python3.12/site-packages/socketio/async_server.py:608> exception=AssetRectDoesNotExist('<Model: AssetRect> instance matching query does not exist:\nSQL: SELECT "t1"."shape_id", "t1"."width", "t1"."height", "t1"."src" FROM "asset_rect" AS "t1" WHERE ("t1"."shape_id" = ?) LIMIT ? OFFSET ?\nParams: [\'abeff924-818b-45c9-bd75-a63c286f6c7e\', 1, 0]')>
Traceback (most recent call last):
  File "${PLANARALLY_DIR}/server/venv/lib/python3.12/site-packages/peewee.py", line 7285, in get
    return clone.execute(database)[0]
           ~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "${PLANARALLY_DIR}/server/venv/lib/python3.12/site-packages/peewee.py", line 4581, in __getitem__
    return self.row_cache[item]
           ~~~~~~~~~~~~~~^^^^^^
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "${PLANARALLY_DIR}/server/venv/lib/python3.12/site-packages/socketio/async_server.py", line 610, in _handle_event_internal
    r = await server._trigger_event(data[0], namespace, sid, *data[1:])
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "${PLANARALLY_DIR}/server/venv/lib/python3.12/site-packages/socketio/async_server.py", line 637, in _trigger_event
    ret = await handler(*args)
          ^^^^^^^^^^^^^^^^^^^^
  File "${PLANARALLY_DIR}/server/src/auth.py", line 55, in wrapped
    return await fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "${PLANARALLY_DIR}/server/src/api/socket/location.py", line 72, in _load_location
    await load_location(sid, pr.active_location, complete=True)
  File "${PLANARALLY_DIR}/server/src/auth.py", line 55, in wrapped
    return await fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "${PLANARALLY_DIR}/server/src/api/socket/location.py", line 222, in load_location
    await _send_game("Board.Floor.Set", transform_floor(floor, pr), room=sid)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "${PLANARALLY_DIR}/server/src/transform/to_api/floor.py", line 14, in transform_floor
    layers = [transform_layer(layer, pr) for layer in layer_query]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "${PLANARALLY_DIR}/server/src/transform/to_api/layer.py", line 14, in transform_layer
    shapes.append(transform_shape(shape, pr))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "${PLANARALLY_DIR}/server/src/transform/to_api/shape.py", line 68, in transform_shape
    return shape.subtype.as_pydantic(shape_model)
           ^^^^^^^^^^^^^
  File "${PLANARALLY_DIR}/server/src/db/models/shape.py", line 140, in subtype
    return getattr(self, f"{self.type_}_set").get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "${PLANARALLY_DIR}/server/venv/lib/python3.12/site-packages/peewee.py", line 7288, in get
    raise self.model.DoesNotExist('%s instance matching query does '
src.db.models.asset_rect.AssetRectDoesNotExist: <Model: AssetRect> instance matching query does not exist:
SQL: SELECT "t1"."shape_id", "t1"."width", "t1"."height", "t1"."src" FROM "asset_rect" AS "t1" WHERE ("t1"."shape_id" = ?) LIMIT ? OFFSET ?
Params: ['abeff924-818b-45c9-bd75-a63c286f6c7e', 1, 0]
```

**Comment by Kruptein** [comment] 2024-11-12 10:45
It seems to be a regression in the db framework we use, I reported a bug [here](https://github.com/coleifer/peewee/issues/2952), but a quick solution is to downgrade the version of peewee to 3.17.5.

As it actually breaks the db, I'm going to do a hotfix release of 2024.3.

**Comment by Kruptein** [comment] 2024-11-12 12:37
The hotfix downgrade has been merged into dev.

**Closed by Kruptein** 2024-11-12 12:37 UTC
Labels: bug, Server
